import {
  IconAdjustmentsPlus,
  IconAlertTriangleFilled,
  IconEdit,
  IconExclamationCircle,
  IconEyeEdit,
  IconFilterEdit,
  IconHomeEdit,
  IconInfoCircle,
  IconLayoutDashboard,
  IconPlus,
  IconRosetteDiscountCheck,
  IconRosetteDiscountCheckFilled,
  IconShieldCheckFilled,
  IconTrash,
  IconUpload,
  IconUserEdit,
} from "@tabler/icons-react";
import { TiArrowBackOutline } from "react-icons/ti";

export const AppIcons = {
  Plus: IconPlus,
  IconEdit: IconEdit,
  IconTrash: IconTrash,
  IconHomeEdit: IconHomeEdit,
  IconShieldCheckFilled: IconShieldCheckFilled,
  IconExclamationCircle: IconExclamationCircle,
  IconUserEdit: IconUserEdit,
  IconFilterEdit: IconFilterEdit,
  IconEyeEdit: IconEyeEdit,
  IconUpload: IconUpload,
  IconInfoCircle: IconInfoCircle,
  IconRosetteDiscountCheckFilled: IconRosetteDiscountCheckFilled,
  IconRosetteDiscountCheck: IconRosetteDiscountCheck,
  IconLayoutDashboard: IconLayoutDashboard,
  TiArrowBackOutline: TiArrowBackOutline,
  IconAlertTriangle: IconAlertTriangleFilled,
  IconAdjustmentsPlus: IconAdjustmentsPlus,
};
